name: meetme
description: A Discord bot written with nyxx and nyxx_commands.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  image: ^4.1.0
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.3
  nyxx: ^5.0.0
  nyxx_commands: ^5.0.0
  nyxx_interactions: ^4.6.0
  
  
  

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
